spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
  datasource:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: "jdbc:derby:memory:person;create=true"
    username: APP
    password:
  sql:
    init:
      mode: always